service: lambda-proxy-test

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket: ${opt:bucket}

  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "*"
     Resource:
       - arn:aws:s3:::${opt:bucket}*

  apiGateway:
    binaryMediaTypes:
      - '*/*'
    minimumCompressionSize: 1

package:
  artifact: package.zip

functions:
  app:
    handler: lambda_proxy.app.APP
    memorySize: 192
    timeout: 10
    environment:
      CACHE_CONTROL: TEST

    events:
      - httpApi:
          path: /{proxy+}
          method: '*'
          cors: true
